### PR TITLE
feature: Add Pipenv for execution

### PR DESCRIPTION
**Pull request by x10an14**
Just a suggestion on how to use `Pipenv` to ensure that the program runs with its dependencies on anyone's computer.

NB: Given that they have `Pipenv` and `python3` installed. (I belive `Pipenv` might force `python3.7`, but that can be looked into if you so desire).

### CODE REVIEW

**Comment by knorrie** [comment]
Hi,

Thanks for your suggestion and your patience.

The "To run the program" section is outdated yes. But, when updating that, I would be more tempted to just say "Install the program using the package manager of your favorite linux distro.". btrfs-heatmap is currently present in most of them.

Using stuff directly from a git clone makes sense when you want to hack on it, or want to try the latest develop branch commits that are not released yet.

I'm curious what would be the reason to choose for getting btrfs-heatmap from git, and mixing it with python-btrfs from pypi.

What's your own use case?

Hans

**Comment by x10an14** [comment]
> The "To run the program" section is outdated yes. But, when updating that, I would be more tempted to just say "Install the program using the package manager of your favorite linux distro.". btrfs-heatmap is currently present in most of them.

I was unaware of this =)
Should be a perfectly good solution.

> I'm curious what would be the reason to choose for getting btrfs-heatmap from git, and mixing it with python-btrfs from pypi.
What's your own use case?

I didn't think to search through Debian/Ubuntu/Mint `apt search` to see whether this was available as a package.
(Nor am I sure I'd trust a potentially non-causal name collision/correlation).
Thus, since I wanted to run it, I cloned this git repo.

`Pipenv` was due to me not wanting to pollute my global env-space (this of course being one of the main reasons behind `pipenv`/`pyenv`/similar `envs` in the first place).

 x10

**Comment by knorrie** [comment]
I changed the README to just recommend installing the distro package. Whoever wants to mess around with the code should be smart enough to find out how to git clone it.

**Comment by x10an14** [comment]
Fair enough =)

That doesn't address the potential of polluting (or explicitly specifying _only_ primary dependencies and versions - which `pipenv` might offer a solution for) global space / PATH.

Let me know if that's something you might be interested in using this PR for, modified or unmodified.

**Comment by x10an14** [comment]
Tidying up old PRs =)

**Pull request closed without merging**
